import { PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS = {
    SUPER_ADMIN: [
        ...Object.values(PERMISSIONS),
    ],

    OWNER: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.BOOKINGS_VIEW,
        PERMISSIONS.BOOKINGS_EDIT,
        PERMISSIONS.CALENDAR_VIEW,
        PERMISSIONS.SLOT_BLOCK,
        PERMISSIONS.VENUES_VIEW,
        PERMISSIONS.VENUES_EDIT,
        PERMISSIONS.PAYMENTS_VIEW,
        PERMISSIONS.STAFF_VIEW,
    ],

    SUPERVISOR: [
        PERMISSIONS.DASHBOARD_VIEW,
        PERMISSIONS.BOOKINGS_VIEW,
        PERMISSIONS.CALENDAR_VIEW,
        PERMISSIONS.SLOT_BLOCK,
    ],
};